variables:
  MONGO_HOST: ""
  MONGO_PORT: ""
  MONGO_USERNAME: ""
  MONGO_PASSWORD: ""
  MONGO_DB: ""
  GIT_SSL_NO_VERIFY: "true"

stages:
  - build
  - deploy

build:
  stage: build
  image: python:3.9
  script:
    - pip install -r requirements.txt
  artifacts:
    paths:
      - ./
  tags:
   - shell

deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t webcrawler .
    - docker run -p 5000:5000 -d webcrawler
  tags:
      - shell
      - azure 
      - docker-vm
